name: Uno
on:
  pull_request_review:
    types: [submitted]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1

    - name: Run
      run: node index.js
      env: 
        COMMITS: ${{ github.event.pull_request._links.commits.href  }}
        ACTOR_ACTION: ${{ github.actor }}
        GITHUB: ${{ toJson(github) }}
        HEAD:  ${{ toJson(github.head) }}
